[package]
name = "bamqc-io"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-htslib = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = []
